// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9R5o6rkpJ5B-AkbVwGjPQXv8NCDUny1w',
    appId: '1:44709277732:web:9d64810ca98478ef01a8b1',
    messagingSenderId: '44709277732',
    projectId: 'mynotes-bytesnbits-02',
    authDomain: 'mynotes-bytesnbits-02.firebaseapp.com',
    storageBucket: 'mynotes-bytesnbits-02.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATGkLRpXO8nTtFozjravNdMqnzaLWgd2s',
    appId: '1:44709277732:android:c0b5196587383f5e01a8b1',
    messagingSenderId: '44709277732',
    projectId: 'mynotes-bytesnbits-02',
    storageBucket: 'mynotes-bytesnbits-02.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaskMKoPr6FG1Xeb8ZVmGWrv6_dCTpSVY',
    appId: '1:44709277732:ios:009487a220abd4bf01a8b1',
    messagingSenderId: '44709277732',
    projectId: 'mynotes-bytesnbits-02',
    storageBucket: 'mynotes-bytesnbits-02.appspot.com',
    iosBundleId: 'nl.bytesnbits.mynotes',
  );

}